import res12 from '../../../assets/resedential/res12.jpg'
import res11 from '../../../assets/resedential/res11.jpg'
import res10 from '../../../assets/resedential/res10.jpg'
import res9 from '../../../assets/resedential/res9.jpg'
import res8 from '../../../assets/resedential/res8.jpg'
import res7 from '../../../assets/resedential/res7.jpg'
import res6 from '../../../assets/resedential/res6.jpg'
import res5 from '../../../assets/resedential/res5.jpg'
import res4 from '../../../assets/resedential/res4.jpg'
import res3 from '../../../assets/resedential/res3.jpg'
import res2 from '../../../assets/resedential/res2.jpg'
import res1 from '../../../assets/resedential/res1.jpg'
import area from '../../../assets/resedential/area.svg'

const resCards = [
    {
        id: 'res_12',
        src: res12,
        title: `Вариант Z-65 «Bavaria»`,
        description: `Стильный и уютный дом с большими панорамными окнами, который идеально сочетает современные архитектурные решения и природные материалы. Просторная гостиная с видом на сад и открытая терраса создают атмосферу уюта и спокойствия.`,
        time: 30,
        type: `Виллы`,
        areaSrc: area,
        area: 135,
        price: 1000000,
        images: [res12, res11, res10, res12, res11, res10],
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_11',
        src: res11,
        title: `Вариант ST-56 «Barcelona»`,
        description: `Классический дом с мансардой, оформленный в традиционном стиле. Удобные спальни, светлая кухня и просторная гостиная делают его идеальным выбором для семьи, которая ценит комфорт и гармонию.`,
        time: 28,
        type: `Дома из профилированного бруса`,
        areaSrc: area,
        area: 249,
        price: 2800000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_10',
        src: res10,
        title: `Вариант ST-25 «Garden ECO»`,
        description: `Дом в стиле минимализма, где простота форм и максимальная функциональность создают уникальное пространство для жизни. Большая терраса для отдыха на свежем воздухе и открытая планировка – идеальный выбор для ценителей чистоты и простоты.`,
        time: 16,
        type: `Усадьбы`,
        areaSrc: area,
        area: 71,
        price: 580000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_9',
        src: res9,
        title: `Вариант ST-53 «Feeria»`,
        description: `Экологически чистый дом с солнечными панелями на крыше, система водоснабжения с использованием дождевой воды и энергосберегающие технологии. Идеально подходит для тех, кто заботится об окружающей среде.`,
        time: 18,
        type: `Дачи`,
        areaSrc: area,
        area: 53.6,
        price: 980000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_8',
        src: res8,
        title: `Вариант LX-75 «JULIA»`,
        description: `Просторный дом с бассейном на заднем дворе. Открытая кухня-студия, уютная гостиная с камином и отдельная зона для отдыха на свежем воздухе создают идеальные условия для комфортной жизни и развлечений.`,
        time: 30,
        type: `Коттедж`,
        areaSrc: area,
        area: 187,
        price: 235000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_7',
        src: res7,
        title: `Вариант ST-49v2 «Nevada»`,
        description: `Практичный и функциональный двухэтажный дом с гаражом, удобным для большой семьи. Просторные комнаты, включая кабинет, несколько санузлов и большая кухня, обеспечат комфортное проживание.`,
        time: 18,
        type: `Каркасные дома`,
        areaSrc: area,
        area: 146,
        price: 2410000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_6',
        src: res6,
        title: `Вариант OS-77 «Milano»`,
        description: `Уютный дом в стиле шале с использованием дерева и камня, создающий атмосферу тепла и уюта. Камин в гостиной и стильная кухня-студия делают этот дом идеальным для зимних вечеров.`,
        time: 30,
        type: `Особняки`,
        areaSrc: area,
        area: 192,
        price: 3260000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_5',
        src: res5,
        title: `Вариант ST-22 «Classic»`,
        description: `Дом в стиле лофт с высокими потолками и открытыми перекрытиями. Современная планировка с минимальными перегородками и индустриальными элементами придает дому уникальность и индивидуальность.`,
        time: 36,
        type: `Дома из оцилиндрованного бруса`,
        areaSrc: area,
        area: 131,
        price: 1200000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_4',
        src: res4,
        title: `Вариант LX-70 «Boston»`,
        description: `Дом с элегантным внешним видом и современными технологиями. Просторные гостиные и спальни, а также функциональная кухня-студия – идеальный выбор для большой семьи.`,
        time: 28,
        type: `Дома под ключ`,
        areaSrc: area,
        area: 232,
        price: 2100000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_3',
        src: res3,
        title: `Вариант ST-38 «Lux»`,
        description: `Великолепный двухэтажный дом с балконом и террасой. Просторные спальни, несколько санузлов и уникальная зона отдыха обеспечат максимальный комфорт для семьи.`,
        time: 24,
        type: `Модульные дома`,
        areaSrc: area,
        area: 136,
        price: 2150000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_2',
        src: res2,
        title: `Вариант ST-66 «Ural»`,
        description: `Просторный и удобный дом с несколькими спальнями и санузлами. Уютная гостиная с камином и зона отдыха на открытом воздухе – идеальное место для отдыха всей семьей.`,
        time: 30,
        type: `Резиденции`,
        areaSrc: area,
        area: 200,
        price: 3400000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    },
    {
        id: 'res_1',
        src: res1,
        title: `Вариант S-47 «Elbrus»`,
        description: `Классический стиль с современными решениями – этот дом идеально подходит для большого города. Просторные комнаты, терраса с открытым видом и уютный кабинет.`,
        time: 20,
        type: `Модульные дома`,
        areaSrc: area,
        area: 117,
        price: 1800000,
        project: `Финская баня "Франкфурт Medium"`,
        style: `Финский`,
        foundation: `Свайно-винтовой`,
        wallInsulation: `RockWool, 150 мм`,
        roofing: `GrandLine`,
        windows: `Двойной стеклопакет Rehau`,
        facadeFinishing: `Имитация бруса`,
        exteriorPaint: `Tikkurila`,
        interiorFinish: `Имитация бруса`,
        saunaFinish: `Осина`,
        stove: `Термофор Витрувия`,
    }
];


export default resCards;